name: mz_core_example
description: Comprehensive example app demonstrating all mz_core features
publish_to: "none"
version: 1.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  mz_core:
    path: ../
    version: 1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mz_lints:
    path: ../packages/mz_lints

flutter:
  uses-material-design: true
