name: mz_utils
description: A collection of Flutter and Dart utility classes for common development tasks including auto-disposal, controllers, extensions, logging, and throttling.
version: 0.0.1
# homepage:

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
